name: flint_client
description: A powerful, type-safe HTTP client for Dart with interceptors, caching, retries, and comprehensive error handling."
version: 0.0.1
repository: https://github.com/flint-dart/flint-client
homepage: https://flintdart.eulogia.net
issue_tracker: https://github.com/flint-dart/flint-client/issues
example: https://github.com/flint-dart/flint-client-sample
environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.9.0
  clock: ^1.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# Project metadata

